#日志
logging:
  level:
    com.woniuxy.clinic.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.43.122.154:3307/clinic?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: dev_clinic
    password: devclinic
  jackson:
    date-format: yyyy-MM-dd
    time-zone:
      GMT+8
  mvc:
    date-format: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
        
mybatis:
  type-aliases-package: com.woniuxy.clinic.entity
  mapper-locations:
  - classpath:/mybatis/mapper/*Mapper.xml
server:
  port: 80
