#日志
logging:
  level:
    com.woniuxy.clinic.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.43.122.154:3307/clinic?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: dev_clinic
    password: devclinic
pagehelper:
  helperDialect: mysql
  reasonable: true 
  supportMethodsArguments: true 
  pageSizeZero: false #pageSize=0 
  params: count=countSql
